=== ByteBrawl-Consulting/Consultoria-E-Sports/Lenguaje de Marcas/Fase 3/resultados_todas_jornadas.dtd
<!ELEMENT RESULTS (ROW+)>
<!ELEMENT ROW (COLUMN+)>
<!ELEMENT COLUMN (#PCDATA)>
<!ATTLIST COLUMN
    NAME CDATA #REQUIRED
>
<!ELEMENT Jornadas (Jornada+)>
<!ELEMENT Jornada (Enfrentamiento+)>
<!ATTLIST Jornada
    Codigo_Jornada CDATA #REQUIRED
    Numero_Jornada CDATA #REQUIRED
>
<!ELEMENT Enfrentamiento (Codigo_Enfrentamiento, Equipo_Local, Equipo_Visitante, Ganador)>
<!ELEMENT Codigo_Enfrentamiento (#PCDATA)>
<!ELEMENT Equipo_Local (#PCDATA)>
<!ELEMENT Equipo_Visitante (#PCDATA)>
<!ELEMENT Ganador (#PCDATA)>

=== ByteBrawl-Consulting/Consultoria-E-Sports/Lenguaje de Marcas/Fase 3/resultados_todas_jornadas.xml
<?xml version='1.0'  encoding='UTF-8' ?>
<!DOCTYPE RESULTS SYSTEM "resultados_todas_jornadas.dtd">
<RESULTS>
    <ROW>
        <COLUMN NAME="XML_DATA">
            <![CDATA[
            <Jornadas>
                <Jornada Codigo_Jornada="1" Numero_Jornada="1">
                    <Enfrentamiento>
                        <Codigo_Enfrentamiento>1</Codigo_Enfrentamiento>
                        <Equipo_Local>Team Alpha</Equipo_Local>
                        <Equipo_Visitante>Team Bravo</Equipo_Visitante>
                        <Ganador>Team Alpha</Ganador>
                    </Enfrentamiento>
                    <Enfrentamiento>
                        <Codigo_Enfrentamiento>2</Codigo_Enfrentamiento>
                        <Equipo_Local>Team Charlie</Equipo_Local>
                        <Equipo_Visitante>Team Delta</Equipo_Visitante>
                        <Ganador>Team Delta</Ganador>
                    </Enfrentamiento>
                </Jornada>
                <Jornada Codigo_Jornada="2" Numero_Jornada="2">
                    <Enfrentamiento>
                        <Codigo_Enfrentamiento>3</Codigo_Enfrentamiento>
                        <Equipo_Local>Team Alpha</Equipo_Local>
                        <Equipo_Visitante>Team Bravo</Equipo_Visitante>
                        <Ganador>Team Bravo</Ganador>
                    </Enfrentamiento>
                    <Enfrentamiento>
                        <Codigo_Enfrentamiento>4</Codigo_Enfrentamiento>
                        <Equipo_Local>Team Charlie</Equipo_Local>
                        <Equipo_Visitante>Team Delta</Equipo_Visitante>
                        <Ganador>Team Charlie</Ganador>
                    </Enfrentamiento>
                </Jornada>
            </Jornadas>
            ]]>
        </COLUMN>
    </ROW>
</RESULTS>
