=== ByteBrawl-Consulting/Consultoria-E-Sports/Lenguaje de Marcas/Fase 4/clasificacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Clasificaciones">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Clasificacion" type="tclasificacion" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tclasificacion">
        <xs:sequence>
            <xs:element name="compId" type="xs:int"/>
            <xs:element name="Equipos">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Equipo" type="tequipo" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tequipo">
        <xs:sequence>
            <xs:element name="Nombre" type="xs:string"/>
            <xs:element name="Puntos" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== ByteBrawl-Consulting/Consultoria-E-Sports/Lenguaje de Marcas/Fase 3/clasificacion_xsd.xml
<?xml version='1.0' encoding='UTF-8' ?>
<Clasificaciones 
xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" 
xs:noNamespaceSchemaLocation="clasificacion.xsd">
    <Clasificacion>
        <compId>1</compId>
        <Equipos>
            <Equipo>
                <Nombre>Team Charlie</Nombre>
                <Puntos>20</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Alpha</Nombre>
                <Puntos>7</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Delta</Nombre>
                <Puntos>4</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Bravo</Nombre>
                <Puntos>1</Puntos>
            </Equipo>
        </Equipos>
    </Clasificacion>
    <Clasificacion>
        <compId>2</compId>
        <Equipos>
            <Equipo>
                <Nombre>Team Hippie</Nombre>
                <Puntos>5</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Echo</Nombre>
                <Puntos>2</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Foxtrot</Nombre>
                <Puntos>1</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Gamma</Nombre>
                <Puntos>0</Puntos>
            </Equipo>
        </Equipos>
    </Clasificacion>
    <Clasificacion>
        <compId>3</compId>
        <Equipos>
            <Equipo>
                <Nombre>Team Indy</Nombre>
                <Puntos>9</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Jack</Nombre>
                <Puntos>9</Puntos>
            </Equipo>
        </Equipos>
    </Clasificacion>
    <Clasificacion>
        <compId>4</compId>
        <Equipos>
            <Equipo>
                <Nombre>Team Lego</Nombre>
                <Puntos>1</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Krack</Nombre>
                <Puntos>0</Puntos>
            </Equipo>
        </Equipos>
    </Clasificacion>
    <Clasificacion>
        <compId>5</compId>
        <Equipos>
            <Equipo>
                <Nombre>Team Neon</Nombre>
                <Puntos>15</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Omega</Nombre>
                <Puntos>10</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Psi</Nombre>
                <Puntos>5</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Quantum</Nombre>
                <Puntos>3</Puntos>
            </Equipo>
        </Equipos>
    </Clasificacion>
    <Clasificacion>
        <compId>6</compId>
        <Equipos>
            <Equipo>
                <Nombre>Team Rhino</Nombre>
                <Puntos>8</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Sigma</Nombre>
                <Puntos>7</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Tango</Nombre>
                <Puntos>5</Puntos>
            </Equipo>
        </Equipos>
    </Clasificacion>
    <Clasificacion>
        <compId>7</compId>
        <Equipos>
            <Equipo>
                <Nombre>Team Uniform</Nombre>
                <Puntos>4</Puntos>
            </Equipo>
            <Equipo>
                <Nombre>Team Victor</Nombre>
                <Puntos>2</Puntos>
            </Equipo>
        </Equipos>
    </Clasificacion>
</Clasificaciones>
