=== ByteBrawl-Consulting/Consultoria-E-Sports/Lenguaje de Marcas/Fase 4/resultados_todas_jornadas.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="Jornadas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Jornada" type="tJornada" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tJornada">
        <xs:sequence>
            <xs:element name="Enfrentamiento" type="tEnfrentamiento" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="Numero_Jornada" type="xs:int"/>
        <xs:attribute name="Codigo_Competencion" type="xs:int"/>
        <xs:attribute name="Codigo_Jornada" type="xs:int"/>
    </xs:complexType>

    <xs:complexType name="tEnfrentamiento">
        <xs:sequence>
            <xs:element name="Codigo_Enfrentamiento" type="xs:int"/>
            <xs:element name="Equipo_Local" type="xs:string"/>
            <xs:element name="Equipo_Visitante" type="xs:string"/>
            <xs:element name="Ganador" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== ByteBrawl-Consulting/Consultoria-E-Sports/Lenguaje de Marcas/Fase 4/resultados_todas_jornadas_xsd_procedimiento.xml
<?xml version='1.0' encoding='UTF-8' ?>
<Jornadas xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="resultados_todas_jornadas.xsd">
    <Jornada Numero_Jornada="1" Codigo_Competencion="1" Codigo_Jornada="1">
        <Enfrentamiento>
            <Codigo_Enfrentamiento>1</Codigo_Enfrentamiento>
            <Equipo_Local>Team Alpha</Equipo_Local>
            <Equipo_Visitante>Team Bravo</Equipo_Visitante>
            <Ganador>Team Alpha</Ganador>
        </Enfrentamiento>
        <Enfrentamiento>
            <Codigo_Enfrentamiento>2</Codigo_Enfrentamiento>
            <Equipo_Local>Team Charlie</Equipo_Local>
            <Equipo_Visitante>Team Delta</Equipo_Visitante>
            <Ganador>Team Charlie</Ganador>
        </Enfrentamiento>
    </Jornada>
    <Jornada Numero_Jornada="2" Codigo_Competencion="1" Codigo_Jornada="2">
        <Enfrentamiento>
            <Codigo_Enfrentamiento>3</Codigo_Enfrentamiento>
            <Equipo_Local>Team Alpha</Equipo_Local>
            <Equipo_Visitante>Team Charlie</Equipo_Visitante>
            <Ganador>Team Charlie</Ganador>
        </Enfrentamiento>
        <Enfrentamiento>
            <Codigo_Enfrentamiento>4</Codigo_Enfrentamiento>
            <Equipo_Local>Team Bravo</Equipo_Local>
            <Equipo_Visitante>Team Delta</Equipo_Visitante>
            <Ganador>Team Delta</Ganador>
        </Enfrentamiento>
    </Jornada>
    <Jornada Numero_Jornada="3" Codigo_Competencion="1" Codigo_Jornada="3">
        <Enfrentamiento>
            <Codigo_Enfrentamiento>6</Codigo_Enfrentamiento>
            <Equipo_Local>Team Bravo</Equipo_Local>
            <Equipo_Visitante>Team Charlie</Equipo_Visitante>
            <Ganador>Team Bravo</Ganador>
        </Enfrentamiento>
        <Enfrentamiento>
            <Codigo_Enfrentamiento>5</Codigo_Enfrentamiento>
            <Equipo_Local>Team Alpha</Equipo_Local>
            <Equipo_Visitante>Team Delta</Equipo_Visitante>
            <Ganador>Team Alpha</Ganador>
        </Enfrentamiento>
    </Jornada>
    <Jornada Numero_Jornada="1" Codigo_Competencion="2" Codigo_Jornada="4">
        <Enfrentamiento>
            <Codigo_Enfrentamiento>7</Codigo_Enfrentamiento>
            <Equipo_Local>Team Echo</Equipo_Local>
            <Equipo_Visitante>Team Foxtrot</Equipo_Visitante>
            <Ganador>Team Echo</Ganador>
        </Enfrentamiento>
        <Enfrentamiento>
            <Codigo_Enfrentamiento>8</Codigo_Enfrentamiento>
            <Equipo_Local>Team Gamma</Equipo_Local>
            <Equipo_Visitante>Team Hippie</Equipo_Visitante>
            <Ganador>Team Gamma</Ganador>
        </Enfrentamiento>
    </Jornada>
    <Jornada Numero_Jornada="2" Codigo_Competencion="2" Codigo_Jornada="5">
        <Enfrentamiento>
            <Codigo_Enfrentamiento>9</Codigo_Enfrentamiento>
            <Equipo_Local>Team Echo</Equipo_Local>
            <Equipo_Visitante>Team Gamma</Equipo_Visitante>
            <Ganador>Team Gamma</Ganador>
        </Enfrentamiento>
        <Enfrentamiento>
            <Codigo_Enfrentamiento>10</Codigo_Enfrentamiento>
            <Equipo_Local>Team Foxtrot</Equipo_Local>
            <Equipo_Visitante>Team Hippie</Equipo_Visitante>
            <Ganador>Team Hippie</Ganador>
        </Enfrentamiento>
    </Jornada>
    <Jornada Numero_Jornada="3" Codigo_Competencion="2" Codigo_Jornada="6">
        <Enfrentamiento>
            <Codigo_Enfrentamiento>12</Codigo_Enfrentamiento>
            <Equipo_Local>Team Foxtrot</Equipo_Local>
            <Equipo_Visitante>Team Gamma</Equipo_Visitante>
            <Ganador>Team Foxtrot</Ganador>
        </Enfrentamiento>
        <Enfrentamiento>
            <Codigo_Enfrentamiento>11</Codigo_Enfrentamiento>
            <Equipo_Local>Team Echo</Equipo_Local>
            <Equipo_Visitante>Team Hippie</Equipo_Visitante>
            <Ganador>Team Echo</Ganador>
        </Enfrentamiento>
    </Jornada>
    <Jornada Numero_Jornada="1" Codigo_Competencion="3" Codigo_Jornada="7">
        <Enfrentamiento>
            <Codigo_Enfrentamiento>13</Codigo_Enfrentamiento>
            <Equipo_Local>Team Indy</Equipo_Local>
            <Equipo_Visitante>Team Jack</Equipo_Visitante>
            <Ganador>Team Indy</Ganador>
        </Enfrentamiento>
    </Jornada>
    <Jornada Numero_Jornada="2" Codigo_Competencion="3" Codigo_Jornada="8">
        <Enfrentamiento>
            <Codigo_Enfrentamiento>14</Codigo_Enfrentamiento>
            <Equipo_Local>Team Jack</Equipo_Local>
            <Equipo_Visitante>Team Indy</Equipo_Visitante>
            <Ganador>Team Indy</Ganador>
        </Enfrentamiento>
    </Jornada>
    <Jornada Numero_Jornada="3" Codigo_Competencion="3" Codigo_Jornada="9">
        <Enfrentamiento>
            <Codigo_Enfrentamiento>15</Codigo_Enfrentamiento>
            <Equipo_Local>Team Krack</Equipo_Local>
            <Equipo_Visitante>Team Lego</Equipo_Visitante>
            <Ganador>Team Krack</Ganador>
        </Enfrentamiento>
    </Jornada>
    <Jornada Numero_Jornada="1" Codigo_Competencion="4" Codigo_Jornada="10">
        <Enfrentamiento>
            <Codigo_Enfrentamiento>16</Codigo_Enfrentamiento>
            <Equipo_Local>Team Lego</Equipo_Local>
            <Equipo_Visitante>Team Krack</Equipo_Visitante>
            <Ganador>Team Krack</Ganador>
        </Enfrentamiento>
    </Jornada>
    <Jornada Numero_Jornada="2" Codigo_Competencion="4" Codigo_Jornada="11">
        <Enfrentamiento>
            <Codigo_Enfrentamiento>17</Codigo_Enfrentamiento>
            <Equipo_Local>Team Alpha</Equipo_Local>
            <Equipo_Visitante>Team Bravo</Equipo_Visitante>
            <Ganador>Team Alpha</Ganador>
        </Enfrentamiento>
    </Jornada>
    <Jornada Numero_Jornada="3" Codigo_Competencion="4" Codigo_Jornada="12">
        <Enfrentamiento>
            <Codigo_Enfrentamiento>19</Codigo_Enfrentamiento>
            <Equipo_Local>Team Echo</Equipo_Local>
            <Equipo_Visitante>Team Foxtrot</Equipo_Visitante>
            <Ganador>Team Echo</Ganador>
        </Enfrentamiento>
        <Enfrentamiento>
            <Codigo_Enfrentamiento>18</Codigo_Enfrentamiento>
            <Equipo_Local>Team Charlie</Equipo_Local>
            <Equipo_Visitante>Team Delta</Equipo_Visitante>
            <Ganador>Team Charlie</Ganador>
        </Enfrentamiento>
    </Jornada>
</Jornadas>
